title:              UHG Blog
email:              johncoady@shaw.ca
description:        UHG Universal Hyperbolic Geometry, Quadrea of Projective Quadrangle, Quadreal of Projective Quadrilateral
author:             John Coady
baseurl:            "/blog"
url:                "https://jcoady.github.io"

# Social Profiles
twitter_username:   
github_username:    jcoady
facebook_username:  
instagram_username:  johndcoady
linkedin_username:  johndcoady

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
kramdown:
  parse_block_html: true
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
  - jemoji


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      mathjax: true
